#!/bin/bash

if [[ $# == 2 ]]
then
  if [[ -f "$1" && -x "$2" ]]
  then
    if gcc "$1" -o "$2"
    then
      echo "The program will be successfully launched."
      ./"$2"
    else
      echo "Errors occurred during compilation. The program will not be started."
    fi
  else
    echo "You have entered invalid parameters. The parameters must meet the requirements." >&2
    echo "The 1st parameter - source file name." >&2
    echo "The 2nd parameter - exe-file." >&2
  fi
else
  echo "Unexpected number of parameters. There should be 2 parameters."
  echo "The 1st parameter - source file name."
  echo "The 2nd parameter - exe-file."
fi

exit 0
